project_name: portal
before:
  hooks:
    - go mod tidy
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates: ["innovia/{{ .ProjectName }}:{{ .Version }}-amd64", "innovia/{{ .ProjectName }}:latest-amd64"]
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates: [ "innovia/{{ .ProjectName }}:{{ .Version }}-arm64v8",  "innovia/{{ .ProjectName }}:latest-arm64v8"]
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goos: linux
    goarch: arm64
docker_manifests:
  - name_template: innovia/{{ .ProjectName }}:{{ .Version }}
    image_templates:
    - innovia/{{ .ProjectName }}:{{ .Version }}-arm64v8
    - innovia/{{ .ProjectName }}:{{ .Version }}-amd64

  - name_template: innovia/{{ .ProjectName }}:latest
    image_templates:
      - innovia/{{ .ProjectName }}:latest-amd64
      - innovia/{{ .ProjectName }}:latest-arm64v8

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true
