apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "portal.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ template "portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update"]
    resourceNames: ["portal-replica-controller"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ template "portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "portal.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "portal.fullname" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ template "portal.fullname" . }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - update
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ template "portal.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "portal.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "portal.fullname" . }}
    namespace: {{ .Release.Namespace }}
