apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "portal.servingCertificate" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "portal.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  server.key: {{ b64enc .Values.mtls.server_key }}
  server.crt: {{ b64enc .Values.mtls.server_cert }}
  ca_cert.pem: {{ b64enc .Values.mtls.ca_cert }}

